### ISSUE TITLE
баг с QuickView

### ISSUE THREAD

**Issue by AVBL** [FarGroup/FarManager#110]
См. строку с Фото016 на скриншоте.
![far-bug](https://user-images.githubusercontent.com/49921898/58373332-50f8fd00-7f35-11e9-8363-752962f5fe77.jpg)

**Comment by johnd0e** [comment]
Файл приложите

**Comment by AVBL** [comment]
[TTT.LOG](https://github.com/FarGroup/FarManager/files/3219717/TTT.LOG)
Прикладываю обрезанную версию (оставил только самое начало файла), баг на этом обрезке воспроизводится.

**Comment by alabuzhev** [comment]
Far UI is a rectangular block of character cells in a console screen buffer.
Each character takes exactly one cell.
This requires a monospaced (fixed width) font to work properly.
Unfortunalely, the monospaced fonts that come with Windows (Lucida Console, Consolas etc.) are not truly monospaced, because fixed width doesn't play well with Unicode, where some characters must have zero width, and some other (e.g. CJK) - double.

In other words - technically it's a Windows issue: the Console is supposed to be a two-dimensional character array, but it isn't. However, I doubt that they will ever fix it, so far it's getting only worse.

So, no, we don't have a solution for this issue and it has nothing to do with QuickView per se, so I'm closing it.

And, please, use the search before raising new issues. This has already been [discussed](https://forum.farmanager.com/viewtopic.php?t=10970) dozens of times.
