### ISSUE TITLE
do not check nightly builds as release

### ISSUE THREAD

**Issue by michalzobec** [FarGroup/FarManager#153]
hello, can you move nightly builds to another repository and make only regular releases as release? you have 8000 releases - it's not even a little clear.

thank you very much.

**Comment by alabuzhev** [comment]
Moving the nightly builds won't change anything.

You see 8000 releases not because we have 8000 nightly builds, but because we have 8000 tags in the repository, and github UI shows every single tag on the Releases page.
There's an [open discussion](https://github.community/t5/How-to-use-Git-and-GitHub/Tag-without-release/td-p/6255) about that, I suggest you vote / comment there.

**Comment by michalzobec** [comment]
okay, so do not use tags for nightly builds, but only for final releases.

**Comment by alabuzhev** [comment]
Again, out of those ~8100 tags only ~200 are related to nightly builds.
The vast majority of them (~7900) are just tags.

We need a way to easily identify any existing version and access its source, so we increment the build number and create a tag for every change in the code.
It's convenient for us and our users and that's how it's been since 2000.
During these 19 years we used:
- no source control at all
- CVS on a private server
- SVN on another private server
- SVN on Google Code
- SVN on SourceForge
- git on GitHub.

This system survived all that and we can't drop it only because the current hosting has a mental UI.
