### ISSUE TITLE
Copy from Far panel to plugin drops selection in 5420, works fine in 5419

### ISSUE THREAD

**Issue by nightroman** [FarGroup/FarManager#159]
### Scenario simulated by the provided script *Test-Explorer-Incomplete2..ps1*

(1) Plugin copies selected files from the native Far panel to the plugin panel.
Namely: the source panel directory is FARHOME, files and folders are 'FarNet', 'Plugins', 'FarEng.hlf', 'FarRus.hlf'.

(2) Some files are copied successfully ('FarNet', 'FarEng.hlf') and others fail to copy ('Plugins', 'FarRus.hlf').
The failure is simulated for the sake of testing, the plugin just tells the engine that some files are failed.
The FarNet engine in this case restores selection of files that failed ('Plugins', 'FarRus.hlf').
This is how it worked in 5419. In 5420 all files in the source panel are unselected.

### How to run

(1) Required module FarNet\PowerShellFar

(2) Unzip the attached and change to its directory.

(3) Invoke

    ps: Invoke-FarStepper .\Test-Explorer-Incomplete2..ps1

or, for step by step invocation

    ps: Invoke-FarStepper .\Test-Explorer-Incomplete2..ps1 -Ask

As a result, in 5420 it fails at some point (an error dialog is shown) and two panels stay:
(a) the native FARHOME panel with *all files unselected*;
(b) the plugin panel with two successfully copied 'FarNet' and 'FarEng.hlf'

P.S. The zip also contains *Test-Explorer-Incomplete1..ps1*.
This scripts tests similar incomplete delete, copy, move scenarios in *plugin* panels.
It works fine. The problem is about the native panel and its selection after F5.

[_190709_061829_far_case.zip](https://github.com/FarGroup/FarManager/files/3372605/_190709_061829_far_case.zip)

**Comment by alabuzhev** [comment]
Thanks, fixed in 2bda10bb7cc1b74032c94df4abc8ca870264c4fd.

It's worth mentioning that:
- SelectNames is case-sensitive, e.g. it doesn't select "plugins".
- The test expects FarEng.hlf to come before FarRus.hlf, it breaks if the panel is sorted differently.

Also, the signature `int WINAPI PutFilesW(PutFilesInfo* info)` in [FarNet Export.cpp:161](https://github.com/nightroman/FarNet/blob/888472ccf92d5f8b16ec7ca88af952cf995e8b72/FarNet/FarNetMan/Export.cpp#L161) is incorrect, it should be `intptr_t`. Currently it returns `0x00000000ffffffff` (4294967295) instead of `0xffffffffffffffff` (-1). It **will** break one day.

**Comment by nightroman** [comment]
Thank you, I'll try it tomorrow.

And thank you for the notes. The fist two are "fine" for my local testing (names are valid and *global* testing always ensures the default panel states including sorting). The last note looks like a real potential problem, I will investigate/fix.
