### ISSUE TITLE
цветовая раскраска в редакторе и обрезание шрифта

### ISSUE THREAD

**Issue by AVBL** [FarGroup/FarManager#160]
Создаём файл DESCRIPT.ION с одной строкой:
`#G 1`
Открываем в редакторе. Часть "#G" подсвечена красным и правый край G обрезан на пару пикселей. (Я не знаю как сюда загрузить скриншот, поэтому дальше описываю словами). Убираем 1... G становится нормальной, добавляем 1 опять... G сразу обрезается.

ADD: Нажимаем CtrlZ (диалог "Описание файла"), F1 - и в справке в двух последних строках ("Использовать ... по умолчанию" и "Сохранять в UTF8") последние знаки тоже обрезаны.

**Comment by alabuzhev** [comment]
Far is a console application, so it **has no notion** of fonts or pixels.
What you're describing is ClearType rendering issues in Console Host.
I believe most of them have been fixed in recent Windows 10 versions, if not - you can report them [here](https://github.com/microsoft/terminal).

Changing the font or its size might help.
