### ISSUE TITLE
Show git branch name, if directory is a repository

### ISSUE THREAD

**Issue by smithx** [FarGroup/FarManager#226]
В bash можно настроить prompt, чтобы в нём отображалось имя ветки репозитория, в Windows - Far - это фактически shell ), и вот если бы при заходе в каталог с git репозиторием, где-то (заголовок окна панели / prompt / нижняя рамка панели /  подсказка для "F13" / etc...) выводилось бы имя ветки, пожалуйста...

**Comment by alabuzhev** [comment]
This can (and should) be implemented by plugins.

**Comment by smithx** [comment]
OK, by plugins: [GitBranch](https://github.com/smithx/far)

**Comment by alabuzhev** [comment]
@smithx cool, but please don't call FCTL_GETPANELDIRECTORY from threads, it isn't safe.
The conventional way is to call ACTL_SYNCHRO instead, Far will then call ProcessSynchroEventW from your plugin in the main thread.

**Comment by smithx** [comment]
Thanx, it will be reworked, is it allowed to invoke `AdvControl` with `ACTL_REDRAWALL` from my thread ?

**Comment by alabuzhev** [comment]
Only ACTL_SYNCHRO and ACTL_GETWINDOWTYPE are _officially_ supported from threads.
Everything else might work on your machine and explode on someone else's, so better don't.

**Comment by smithx** [comment]
Reworked

**Comment by mirzah** [comment]
I think Git became 1st class citizen on computers, for almost all people using FAR. Maybe you could reconsider introducing full support for git in FAR.

**Comment by alabuzhev** [comment]
@mirzah, smithx wrote a [plugin](https://github.com/smithx/far) that does exactly what the title says. Have you tried it?

**Comment by mirzah** [comment]
Yes, I use it, it is nice! What I mean is little bit different thing: maybe plugin like this (but more complete git integration, like tree viewer, commit, merge with diff in FAR editor, etc.) culd be considered by FAR devs to be part of basic FAR distribution, because I suppose Git is now everywhere where FAR is used, it is almost like extension of file system. There is "giterm" python ncurses app, but is not maintained, and obviously not integrated with FAR. This would be killer plugin imho. :-) Just a thought.
