### ISSUE TITLE
Far disappears when heiw is executed

### ISSUE THREAD

**Issue by Cih2001** [FarGroup/FarManager#302]
Hi, Far has a strange behavior in my machine, Whenever I execute Heiw, it disappears, (does not exit or crash as the process is not terminated in task manager) but the window disappers and cannot be restored. I am using Far version 3.0.5700.0 x64 on windows 10 19042.630.

**Comment by lowtrucks** [comment]
> Hi, Far has a strange behavior in my machine, Whenever I execute
> Heiw, it disappears, (does not exit or crash as the process is not
> terminated in task manager) but the window disappers and cannot be
> restored. I am using Far version 3.0.5700.0 x64 on windows 10 19042.630.

latest version is 3.0.5706.

--
E-mail: lowtrucks@gmail.com
Web site: http://lowtrucks.net/

**Comment by Cih2001** [comment]
Same problem with that version as well.

**Comment by alabuzhev** [comment]
> the window disappers and cannot be restored

This is because in certain situations certain combinations of API calls, performed by hiew, could crash the console host process (conhost.exe), that actually owns and shows the window.

This is a known windows 10-specific bug, reported long ago [here](https://github.com/microsoft/terminal/issues/2366), and apparently earlier [here](https://github.com/microsoft/terminal/issues/1976) and even [here](https://github.com/microsoft/terminal/issues/256), but supposedly fixing crashes is not a high priority kind of task these days.

It looks like there's (finally!) [some progress](https://github.com/microsoft/terminal/pull/8309) - please check the latest console version once available and [report](https://github.com/microsoft/terminal/issues) if it's still there. 

In the meantime I think it can be workarounded by either:
- Starting hiew in a separate window (<kbd>Shift</kbd>+<kbd>Enter</kbd>).
- Switching to legacy console in window properties.
- Reducing the buffer size before launching hiew, e.g. wrapping it in bat file along with something like `mode 80,25`.
