### ISSUE TITLE
Latest Far stable (5800) - FarColorer not loaded on Windows XP SP3

### ISSUE THREAD

**Issue by de77** [FarGroup/FarManager#403]
On Windows XP SP3 last stable Far version 3.0.5800 x86 couldn't load Far Colorer plugin. When launched it showed red window with following text 
"Error loading plugin"
"C:\Program Files\Far3.0\Plugins\FarColorer\bin\colorer.dll"
"0x0000007F - Не найдена указанная процедура."

Dependecy walker (depends.exe) shows following unresolved symbols whitin kernel32.dll - AcquireSRWLockExclusive, GetDynamicTimeZoneInformation, GetLocaleInfoEx, InitializeConditionVariable, InitializeCriticalSectionEx, InitializeSRWLock, InitOnceBeginInitialize, InitOnceComplete, RealizeSRWLockExclusive, SleepConditionVariableCS, SleepConditionVariableSRW, WakeAllCondtionVariable, WakeConditionVariable. Looks like while upgrading colorer broke or dropped support for Windows XP.

**Comment by alabuzhev** [comment]
As far as I know, XP support was deliberately dropped in Colorer 1.4.
You can downgrade to [1.3.26](https://github.com/colorer/FarColorer/releases/tag/v1.3.26) if you like.
@ctapmex could you confirm please?

**Comment by de77** [comment]
Oh, i see. Thanks. Feel free to close this issue.

**Comment by ctapmex** [comment]
yes, WinXP not supported

https://github.com/colorer/FarColorer/tree/master
FarColorer has two main verions:
1.3.x - version with Windows XP support. Latest version included in Far Manager 1.3.26 in Far Manager 3.0.5796 (2021.05.09). This version has partial support. See in branch v1.3.x.
1.4.x and higher - current fully supported version, worked only on actual platforms. It included in Far Manager since 3.0.5797 (2021.05.10).
