### ISSUE TITLE
Проблемы с диалогами после b5788 Git-15646640d (регрессия)

### ISSUE THREAD

**Issue by skipik** [FarGroup/FarManager#406]
Репорты и подробности проблем:
1. https://forum.ru-board.com/topic.cgi?forum=5&topic=50439&start=2360#21
2. https://forum.ru-board.com/topic.cgi?forum=5&topic=50439&start=2340#12
3. https://forum.ru-board.com/topic.cgi?forum=5&topic=50439&start=2380#10
4. https://github.com/VictorVG/latest/issues/14

**Comment by HamRusTal** [comment]
Также https://forum.farmanager.com/viewtopic.php?p=166621#p166621

**Comment by alabuzhev** [comment]
@skipik, all that is very interesting, but this an issue tracker.
If there are issues, please report them *separately* and *properly*.
No one has time to go through that stream of consciousness and separate the wheat from the chaff.

Thank you for understanding.

**Comment by skipik** [comment]
Ok, I'm sorry. Will do it that way next time.

**Comment by shmuz** [comment]
@alabuzhev , да, репорты оставляют желать лучшего.
Но там же приведена картинка диалога плагина IntChecker, где радиобаттоны наполовину (правые скобки) окрашены в другой цвет, ну и другие артефакты присутствуют.
Разве этого недостаточно?

**Comment by alabuzhev** [comment]
> IntChecker, где радиобаттоны наполовину (правые скобки) окрашены в другой цвет

Please report [IntChecker bugs](https://github.com/lazyhamster/IntChecker/blob/e2a068a6afa6b64a923b5f5e3342c604e7605aa3/source/IntChecker2-Far3.cpp#L676-L679) to its maintainer.

**Comment by skipik** [comment]
Ok.
But what about these -> https://forum.ru-board.com/topic.cgi?forum=5&topic=50439&start=2340#12 and https://forum.ru-board.com/topic.cgi?forum=5&topic=50439&start=2360#5
There are only bug reports, no useless information. And about the FAR bug, not the plugins one.

**Comment by alabuzhev** [comment]
@skipik, I'm aware of that one, it's already being discussed [here](https://forum.farmanager.com/viewtopic.php?f=36&p=166625#p166625).

As already mentioned there - yes, the behaviour is slightly different now, but I'm not convinced yet that it's worse than before.
It's kinda more logical (the state belongs to the control, not to its content) and makes it more noticeable and harder to miss.
I haven't seen yet any reasonable arguments against it (*"I don't like it"* isn't an argument). If you can come up with such arguments (e.g. *"it makes my work harder because this and that"*) - please feel free to post them.
