### ISSUE TITLE
Rejecting elevation request when saving a file prevents from a further saving

### ISSUE THREAD

**Issue by montoner0** [FarGroup/FarManager#407]
The issue #307 reminds me about this one which is 100% reproducible:
1. Try to save a file without permissions
2. Reject the elevation request
3. Try to save it again
4. No more elevation requests and immediate "access denied" error

The only way to save the file after this is to save it in a different folder where you have permissions
![image](https://user-images.githubusercontent.com/13542804/120107929-962b1780-c16b-11eb-8092-17a07682ecc0.png)

**Comment by alabuzhev** [comment]
It's kinda by design.
To minimise the number of requests the choice is remembered until things settle down.
"Settle down" here basically means "we're in panels and nothing happens".
So just switch to panels and back if you changed your mind.

I guess this condition can be extended to cover the editor as well, but it never bothered me enough to change it.

**Comment by montoner0** [comment]
As by me it's pretty strange and counterintuitive design. Since a user can't guess it in any way it looks like a bug, not a feature.

**Comment by montoner0** [comment]
And more - there's an option in the elevation dialog "don't ask in this session" which is a clear way to say "I don't want it anymore". Why there's no such option for this case?

**Comment by alabuzhev** [comment]
Ok, 5808.
