### ISSUE TITLE
Can't activate account on the developers forum

### ISSUE THREAD

**Issue by yuchdev** [FarGroup/FarManager#421]
The issue is not about Far itself, so sorry about that. Please, do not delete the issue, I really need assistance.
I wanted to ask several questions about possible contributions to Far Manager, but I can't activate my newly created account on the forum. I tried activation through Github, email addresses from Protonmail or Mailfence, and did not receive any confirmation email, including the Spam catalog. 
The "Contact Us" form of the forum seems to be disabled by the administrator.
I hope, someone from the forum administration should be present here, so I ask for help.

**Comment by alabuzhev** [comment]
The site and the forum are hosted by http://trunkmobile.ru, which, as the domain suggests, is physically located in a jurisdiction known for its obsession with blocking.

Anticipating "but why?" - because it's provided by one of the project contributors for free and it's better than nothing.

I've activated your protonmail account manually, but note that you still won't get any emails from the system. Try using gmail or something else that isn't blocked by them yet.

You're also welcome to discuss anything [here on Github](https://github.com/FarGroup/FarManager/discussions).

**Comment by yuchdev** [comment]
Oh, missed your message.

Many thanks for the help, if possible, could you delete my second attempt to create account, using Mailfence?

Probably, some free option to set up the VPN tunnel could be considered as a solution.
I understand it is probably not a critical issue, until no one is complaining, but probably I could help (at least myself).

Kind Regards,
Yurii Cherkasov

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by alabuzhev** [comment]
Deleted.
If you're aware of reliable free VPN tunnels and if it's possible to use one for egress email traffic only - please let us know.
