### ISSUE TITLE
Unexpected delay between pressing F3 and showing the window

### ISSUE THREAD

**Issue by bOOT-CoDe** [FarGroup/FarManager#469]
### Far Manager version

3.0.5888.0

### OS version

10.0.19042.1288

### Monitor, display settings and console configuration
***Windows***
- screen resolution: UHD (2560px x 1440px)
- orientation: landscape
- scaling factor: 100%
- task bar location: bottom
- task bar height: two button rows
- task bar button size: small

***Far console***
- console type: new console
- code page: 852 (OEM - Latin II)
- font: Consolas
- font size: 20 

### Steps to reproduce

1. maximize Far Manager window (ALT+F9)
2. set the cursor over file with any file extension of these: exe, pdf, jpg, dll (some others may be affected too)2. 
3. press F3
4. wait...

### Expected behavior

the window with file content appears at almost instantly
- this is the behavior seen in Far Manager version 5.0.5800, 64-bit version

### Actual behavior

there is very noticeable delay between pressing F3 and showing the window
- the delay vary between 0.5 s to 3 s even on very small files
- sometimes after the daly only some part of the window is filed with file content (filled continuously by whole rows from top to some row) and after some small additional delay the rest of the window is filled by the rest of file content
- the delay it is not observed on all file extensions but only on certain file extensions
  - but most probably the content of the file is the real cause of the problem
- this delay was introduced somewhere after stable version 3.0.5800.0
- this delay is still present in nightly build 3.0.5912.0 (last build at the moment)

**Comment by alabuzhev** [comment]
The viewer doesn't care about file extensions and processes all files equally (unless you have your own associations that do something else).
The list of affected extensions suggests that you might have a paranoid antivirus. Try turning it off.

**Comment by bOOT-CoDe** [comment]
I test several versions of Far on the same computer on the same files, so antivirus cannot be the problem - but I test that anyway and the issue is still there. But later I realized that the problem occurs only in maximized Far window. So I updated description of the bug. I am now back on Far 5.0.5800 which doesn't have this issue.

**Comment by bOOT-CoDe** [comment]
I uploaded one PDF file which cause the 1 s delay in maximized window.
[comirnaty-epar-product-information_cs.pdf](https://github.com/FarGroup/FarManager/files/7479766/comirnaty-epar-product-information_cs.pdf)

**Comment by alabuzhev** [comment]
It is easy to check whether it's about the file content or the extension - try renaming the file and see if the issue is still there.
If it's about the content indeed, reducing the file size until the problematic character is found could help.
Also, what code page does the viewer show when you open these files?

**Comment by yegor-mialyk** [comment]
@alabuzhev, I can reproduce it with any file that has random content (just generated a test 64 MB file with random bytes).

For better effect I changed the console font size to 8 from 16 (Consolas) and ran Far at full screen (Alt-F9) as mentioned above.

The interesting thing is:
I have 1251 as a default code page in Options -> Viewer Settings. I take a second or two to open the test file in the viewer.

But if I change the default code page to 866 OEM, Far Manager starts to open the same test file instantly in any resolution.

Hope it helps.

**Comment by alabuzhev** [comment]
@yegor-mialyk I still can't reproduce it.
Could you try to pinpoint the problematic character(s)? CP1251 only has 256, so it shouldn't be too hard.

**Comment by yegor-mialyk** [comment]
At least 152 (98h)

**Comment by alabuzhev** [comment]
We don't print 98h at all, because it's a control character:
https://github.com/FarGroup/FarManager/blob/6a2c5f4d444385a0b3312a54606ce5c514755daa/far/console.cpp#L139

What do you *actually* see - 98h or E098h? (you can use edit, mark, copy commands from the system menu to find out).

**Comment by yegor-mialyk** [comment]
You are right, it is E098h actually if I copy it through Windows' mark/copy.

**Comment by alabuzhev** [comment]
Interesting.
That range of characters is [considered ambiguous](https://github.com/microsoft/terminal/blob/7aae2e9100c392b0c98b1120152bcf9709fcf9f6/src/types/CodepointWidthDetector.cpp#L246) in the console host (width-wise), so probably the host performs some non-trivial magic to find the width.

Perhaps we should use a different range for C1 replacement. Ideas are welcome.

**Comment by yegor-mialyk** [comment]
˽ <- 02FDh + maybe an ability to change it through lng (for those who do not like it). I personally would accept any (except probably space/empty character as it may introduce some confusion).

**Comment by bOOT-CoDe** [comment]
I have created test files with codes from 0x80 to 0x9F (packed in "[Codes 80 to 9F.zip](https://github.com/FarGroup/FarManager/files/7516272/Codes.80.to.9F.zip)") and tested them in the internal viewer in FAR 3.0.5800 and FAR 3.0.5912. In the viewer I tried several code pages. The problem doesn't occur in FAR 3.0.5800 but it occurs in FAR 5.0.5912. For sure several ANSI code pages are affected but the codes causing problems differs across code pages. The problematic codes are undefined in the standard of the affected ANSI code pages, for example:
- ANSI 1250: codes 0x81, 0x83, 0x88, 0x90, 0x98
- ANSI 1252: codes 0x81, 0x8D, 0x8F, 0x90, 0x9D

When I copy out (by the system menu in the left top corner of the FAR window) the character displayed in FAR 3.0.5800 the character code is exactly the code in the file and 1 byte long. But if I copy out the character displayed in FAR 3.0.5912 the character code is prefixed by 0xE0, so the character code length is 2 bytes in ANSI view, but ANSI code pages are essentially single byte character encodings. This is the only difference I have found and it drastically affect the performance.

**Comment by alabuzhev** [comment]
@bOOT-CoDe, thanks for confirming.
As I wrote earlier, 80-9F are control codes and applications like Far are not really supposed to output them directly.
Yes, it worked for decades because the console host was simply ignoring their control meaning, but it changed recently and now the host treats them as control characters and breaks the output completely if we don't replace them with something else. You can find the details in the linked issue just above your comment.
The choice of the E080 - E09F range is (almost) arbitrary.
The other possible options are:
- Different codepoints within the PUA (E000 - F8FF)
- Different rare codepoints within the BMP
- Just replace all of them with FFFD (�). I think I'll pick this one.

**Comment by alabuzhev** [comment]
5915.

**Comment by bOOT-CoDe** [comment]
The build 5915 restored the performance. Thank you @alabuzhev.

I read what was written before but I got quite confused as the codes in the block 80-9F in ANSI code page are not defined as control codes in ANSI code pages (unlike ISO 8859 character encodings) but as the regular characters, except a few undefined codes, which are not control codes neither, and it took me a while before I understand (hope finally right) that you have some-how deal with undefined codes, and if we want to display them using wide-character API, you have to remap them to codepoint(s) of some glyph/s) and the first choice was not so great from performance perspective.

I can also confirm that in FAR between builds 5811 and 5814 inclusive the ISO 8859-2 encoding was affected too for whole block 80-9F and in this encoding these codes are really the C1 control codes. In FAR build 5915 the viewer works fast again even with ISO 8859 encoding with any of the code from the C1 block.

**Comment by alabuzhev** [comment]
Great, then we can probably close this one?

P.S. Of course, the performance would still be suboptimal if you encounter *real* E098 etc. in UTF-8/UTF-16 files, but that is expected to be too rare to worry about.

**Comment by alabuzhev** [comment]
> if we want to display them using wide-character API, you have to remap them to codepoint(s) of some glyph/s)

Yes, you understand correctly: all the output is performed in Unicode, using wide-character API, the input code page only defines how to represent each byte in Unicode. Some codepages have undefined codes and MultiByteToWideChar maps them to Unicode *as is*.

For example, if you have a file in [code page 1250](https://en.wikipedia.org/wiki/Windows-1250) with bytes 0x80 and 0x81, converting it to Unicode will produce the Euro sign, `'€'` (`(wchar_t)0x20AC`) and... `(wchar_t)0x81`, because 0x81 has no mapping in 1250:
```C++
wchar_t w[2];
MultiByteToWideChar(1250, 0, "\x80\x81", 2, w, 2);
assert(w[0] == 0x20AC);
assert(w[1] == 0x81);
```
But in Unicode 0x81 suddenly has a quite different meaning - "High Octet Preset", and printing it and other C1 codes can lead to surprising results, so we should replace them with something, same as with, for example, 0x7 - if we don't, it will beep all over the place.

It is worth mentioning that this replacement happens in the drawing layer only. Any text copied from the viewer, editor, internal screen grabber etc. *using Far own facilities* will contain the original codepoints.

**Comment by bOOT-CoDe** [comment]
I agree, we can close this issue.
