### ISSUE TITLE
HLFView и хелпы в UTF-8 без BOM

### ISSUE THREAD

**Issue by VictorVG** [FarGroup/FarManager#5]
Много говорить не надо - и так всё видно :)

![1](https://user-images.githubusercontent.com/906886/32440549-b2157d6e-c304-11e7-9c33-494727fcda0f.png)

хелп берём к примеру из этого плагина - [**LUA File List**](https://plugring.farmanager.com/plugin.php?pid=944) lflist_ru.hlf ([lflist_ru.hlf.zip](https://github.com/FarGroup/FarManager/files/1446126/lflist_ru.hlf.zip)). Файл кодирован в UTF-8, но BOM нет - получаем что видим.  Перекодировка в редакторе с BOM устраняет явление, но перекодировать все плагины.:) 

Ситуации сто лет в обед, у меня выплыла сегодня. Я думаю что возможным решением может быть добавление переключателя кодировки как у вьера/редактора - врядли кто перекодирует все UTF-8 хелпы в форму с BOM, да и говорят что "_BOM это зло_", но отсутствие сего "зла" вылезает такими "красотами".:)

**Comment by VictorVG** [comment]
У себя с проблемой только этот файл отыскал, устранил перекодировкой с BOM.

**Comment by alabuzhev** [comment]
There is no codepage detection for help and language files.
It's either explicitly specified with BOM or system OEM (for compatibility with old plugins).
This behaviour has not changed since 2009, which means that any plugin author should be aware of it by now.
There are no plans to change this in the foreseeable future.

**Comment by VictorVG** [comment]
Ok! I just save file as UTF-8 BOM,
