### ISSUE TITLE
can't download far

### ISSUE THREAD

**Issue by brendan24** [FarGroup/FarManager#61]
i can't download far

1) main website - timeout
2) no mirrors!
3) alternative downloads - with viruses!

AAAAAAAAA what's a fuck!

**Comment by Vict0rC** [comment]
same problem last few days... official download site is down...

**Comment by lowtrucks** [comment]
@brendan24, if you asked not in demanding and rude manner, i would give you a link for alternative source with latest pre-compiled Far. but i don't deal with assholes.

**Comment by Vict0rC** [comment]
Sorry, but it was not a rude manner, it was just a statement of fact, nothing more. I'm afraid your reaction is rather rude manner. With such an approach to your unofficial compilation, no one will be interested.
Thanks.

**Comment by lowtrucks** [comment]
@Vict0rC,

1. if you re-read my previous message, you'd see, it's directed to @brendan24.
2. it's not my compilation.

**Comment by Vict0rC** [comment]
I'm sorry, my mistake, I overlooked it.

**Comment by OneMoreAgain** [comment]
@lowtrucks and anyone else who notices this issue, and can check / respond:
Folks, this is a problem, indeed. Personally I don't really demand a download (I have an old copy, thanks), but the whole farmanager.com domain is offline for a second consecutive week (!!!), last reported available 2 August 2018 by engines commonly found by "is it down or just me" search. So the official forum/bugreport are not reachable, everything is down. Last post on twitter from @farmanager is 2 Aug 2016 (!!!). The Facebook page of "Far Manager - internet company" has the last post on 3 August 2018, proudly announcing the "Far Manager 3.0 Build 5252 Stable" available on Live-new.com. This live-new.com does not host the binaries, and download links point back to the dead farmanager.com download page.
And I wasn't able to find a note anywhere that would explain what's going on. What, everyone died? Or released the build and gone vacationing/celebrating like there's no tomorrow? That's how it looks for end users. So I will second the @brendan24 's "WTF" comment, because this is exactly the FTW situation. This is *not acceptable* for an entity calling itself an "Internet company". Developer, even of a free and narrow niche non-mainstream product has responsibility to keep users informed, that's fundamental.
This project page on github is under FarGroup, so it is has official status, otherwise I would not bug unrelated people.
If anyone has better update, please post here (unless there is anything new on the official page)

**Comment by shmuz** [comment]
@OneMoreAgain , I'm a member in FarGroup and despite that I know nothing about the current state of the server and what's going on with it. In the past there have been cases like that, I hope that the server will return to normal functioning in a few days, maybe tomorrow.

**Comment by AndrewSav** [comment]
The site seems to be back online. Yay!

**Comment by alabuzhev** [comment]
> The Facebook page of "Far Manager - internet company"

It is a scam - we do not have a facebook page.

> This is not acceptable

I would like to remind all the experts in this thread that this is a non-commercial and non-profitable project, supported by a group of individuals in their spare time and provided, according to the license, "as is" and without any warranty.

The web hosting is provided by a volunteer for free, we are happy with it and not asking for more.

If you are willing to provide a better hosting (or mirrors) for the same price - you are welcome.

If you are willing to monitor the server availability 24/7/365 and keep the users informed (via facebook / twitter / postcards / whatever) for the same salary - you are welcome.

If you prefer to lecture us how to do things - you are welcome to read the above again.
