### ISSUE TITLE
при сохранении в редакторе портятся некоторые знаки в однобайтовых кодировках

### ISSUE THREAD

**Issue by AVBL** [FarGroup/FarManager#639]
### Far Manager version

последняя стабильная

### OS version

Windows 10.0.19045.2604

### Steps to reproduce

1. Создаёте новый файл (Shift-F4) - имя и кодировка (OEM, ANSI) не играют роли
2. Вводите, например, знак с кодом 128 (включаете Numlock и нажимаете Alt-128 на цифровой части клавиатуры).
3. Сохраняете (F2).
Получаем предупреждение:
![image](https://user-images.githubusercontent.com/49921898/221272187-f95784e8-b0b6-42ff-8884-aefebf84d4dc.png)
В диалоге всё равно выбираем "Сохранить", выходим, открываем файл - видим знак с другим кодом (63).

PS: Мне понадобилось отредактировать нетекстовый файл настроек одной игры (она сама зависала при изменении настроек). К сожалению, редактирования в режиме дампа-кода нет, я попытался отредактировать в текстовом виде и обломался.

### Actual behavior

*

**Comment by MKadaner** [comment]
Сказано же русским по красному, "Сохранять файл не рекомендуется." Так ведь нет, надо попробовать.

ОК. Иногда мне случается редактировать нетекстовые файлы Far'ом. Этот режим, вообще говоря, не поддерживается, так что действовать надо методом проб и ошибок.

Попробуйте открыть файл в кодировке `65001 UTF-8`. Байт с кодом 128 сам по себе не является допустимой UTF-8 последовательностью, но, к счастью (или к несчастью), Far'овкий встроенный редактор очень толерантен к ошибкам кодировки UTF-8, так что он просто сохраняет весь мусор, который Вы введёте.

И обязательно побайтно сравните отредактированный файл с исходным и убедитесь, что Вы получили то, что хотели.

```
fc /b "My Old Garbage bin" "My New Garbage bin"
```

**Comment by AVBL** [comment]
> не рекомендуется."
> действовать надо методом проб и ошибок

Есть же ведь разница между "не рекомендуется" и "я сейчас испорчу". И ведь это место вроде как предназначено в том числе для того, чтобы разбираться со случаями, когда приходится решать задачу не прямо, а пробами и ошибками. Нет?

> Попробуйте открыть файл в кодировке 65001 UTF-8

Постараюсь запомнить на будущее, но сейчас я решил проблему иначе, плагином Hexitor. Вопрос в том, что, как мне кажется, проблема есть и плагин её не решает, а маскирует.

**Comment by alabuzhev** [comment]
Editor input is in Unicode and has nothing to do with codepages.
Alt+128 is [U+0080 Padding Character](https://www.compart.com/en/unicode/U+0080).
[CP866](https://en.wikipedia.org/wiki/Code_page_866) does not contain `U+0080 Padding Character`.
And this is exactly what the message says and why saving is not recommended.
In general, we assume that users are able to read and understand warning signs.
If you want [U+0410 Cyrillic Capital Letter A](https://www.compart.com/en/unicode/U+0410), which is 128 in CP866, type Alt+1040.

**Comment by AVBL** [comment]
Полагаю, я был неправильно понят. Мне НЕ нужно было U+0410, мне был нужен конкретный код без трансляции. При этом обращаю внимание: если этот код уже загружен из файла при открытии, то при сохранении он не будет испорчен, а вот если этот код введу я, то он уже будет испорчен. Расмотрим на примерах. Открываю файл настроек:
![image](https://user-images.githubusercontent.com/49921898/221359955-84490617-4227-46d7-80f6-ac23eef9ad2f.png)

Видно, что на второй позиции код 128 (в статусе отображается как 1026/128; при переключении на кодировку OEM там появляется префикс "1040/"). При сохранении этого файла он остаётся неизменным. Теперь вводим код 128 вручную (Alt-128):
![image](https://user-images.githubusercontent.com/49921898/221360073-d32e7a8f-0f60-4e4c-8b49-c39f3f3867f3.png)

Можно видеть, что код тот же - 128, но отображается он иначе и в статусной строке у него нет префикса "1026/". Соответственно, при сохранении файла начинаются проблемы с предупреждениями и порчей кодов.

Иными словами, можно сказать, что баг заключается в том, что код, считанный из файла, и тот же код, введённый с помощью клавиатуры, обрабатывается редактором по разному (хотя, полагаю, при вводе кода с клавиатуру он должен обрабатываться так же, как при взятии из файла).

PS: Я хотел сначала обсудить этот вопрос в привате, но не нашёл здесь привата.

**Comment by MKadaner** [comment]
First of all, my apologies. I was wrong when I suggested using code page UTF-8 to manipulate non-text files. It won't help. Codepoint U+0080 will be saved to the file as a sequence of two bytes, 0xC2 0x80.

> код, считанный из файла, и тот же код, введённый с помощью клавиатуры, обрабатывается редактором по разному

Of course! The code read from a file will be decoded, while the code entered from the keyboard is used as is. These codes are in different "languages" if you wish. Code pages serve as "dictionaries" which allow to "translate" between these "languages."

---

Let me explain all this in more words (and in English) for the benefit of other users who may also be confused, because the topic is indeed difficult to wrap one's head around, especially if one does not eat character encodings for breakfast.

Let's start with a bit of terminology (somewhat informally):

1. `Byte` is an 8-bit value in a file. Bytes do not have any relation to characters, languages, or encodings.
2. `Character` is a letter in some alphabet. Some characters, or rather alphabets may be quite weird, consider, for example, this one: 🐈.
3. `Codepoint` is a numerical code or a number assigned to some characters by Unicode Standard.
4. `Encoding` as a noun is a well-defined way to interpret sequences of codepoints as sequences of bytes and vice versa. One may call it a mapping between (sequences of) codepoints and (sequences of) bytes.
   - `Encoding` as a verb is the process of transforming the given sequence of codepoints to the sequence of bytes according to a certain encoding.
   - `Decoding` as a verb is the process of transforming the given sequence of bytes to the sequence of codepoints according to a certain encoding.
5. `Code page` is a number (and usually a conventional name) assigned to an encoding. The words "encoding" and "code page" sometimes used interchangeably.
6. `File` is a sequence of bytes. Unless a specific encoding is somehow associated with the file, the question of what codepoints or characters this file contains is moot.

There are few interesting facts about encodings:

1. The same sequence of bytes can be decoded according to different encodings resulting in different sequence of codepoints.
2. Some sequences of bytes cannot be decoded in some encodings.
3. Some sequences of codepoints cannot be encoded in some encodings.
4. Some encodings (code pages) are designed to allow encoding of all valid codepoints. These encodings are informally called "Unicode." Examples include UTF-8, UTF-16, and (ahem) UTF-7.
5. There are encodings which use exactly one byte to represent each codepoint. They are informally called single byte character sets (SBCS). Obviously, such encodings are very limiting. They allow to encode no more than 256 different codepoints.
   - Most (all of?) these encodings define one-to-one mapping between exactly 256 codepoints and 256 possible values which can be represented by one byte.
   - Such encodings allow to decode any sequence of bytes by simply replacing each byte with its corresponding codepoint.
   - An important property of such encodings is that they support round trip bytes-codepoints-bytes. This means that if a byte sequence was decoded according to such encoding, and later the resulting codepoint sequence was encoded (according to the same encoding), the final byte sequence will match the original one byte for byte.
   - Most (all?) ANSI and OEM code pages are SBCS.

How the internal Far Editor works?

1. The editor chooses encoding to associate with a given fille. It may autodetect (guess) it, or the user may specify the encoding explicitly.
2. The editor decodes the sequence of bytes in the file according to the selected encoding. The result is the corresponding sequence of codepoints (characters) the editor allows the user to modify.
3. It's important to reiterate that the editor operates on the sequence of codepoints. I intentionally avoid the question of what it means and how it is implemented.
4. The editor observes user's input as _codepoints_. No matter what input method the user chooses, the end result which the editor receives is a codepoint. Particularly, Alt+NNNN allows to enter codepoints directly.
5. The editor inserts the entered codepoint into the codepoint sequence being edited.
6. When the user saves the work to the file, the editor encodes the codepoint sequence according to then-current encoding. This encoding may be different from the one used to originally decode the file.

This is not to say that it's the only way to implement an editor, but this is how the internal Far editor works.

---

Having read and understood all these explanations, please re-read Mr. Alabuzhev's comment above.

**Comment by AVBL** [comment]
> The editor observes user's input as codepoints. No matter what input method the user chooses, the end result which the editor receives is a codepoint.

Это не совсем так. Если я введу с клавиатуры, например, букву "а", то в кодировке OEM она будет иметь код 1072/160, а в кодировке ANSI - 1072/224.
![image](https://user-images.githubusercontent.com/49921898/221415114-00926796-26dd-440f-9a80-efbf8776a253.png)
То есть первичное кодирование редактор проводит и хранит не только кп, но и получившееся значение (в данном случае байт), которое уже и использует при смене кодовой страницы (в результате при смене ANSI на OEM код 1072/224 меняется на 1088/224).

> 6. user saves the work to the file, the editor encodes the codepoint sequence according to then-current encoding.

Вариант первый, а нужно ли вообще менять (транслировать, а точнее необратимо портить знаками вопроса) 256-битные кодепойнт (кп), для которых не нашлось вариантов подстановки, в байтовых OEM/ANSI кодировках? Для кп типа 8221 (закрывающая кавычка ”) можно и предупреждения давать, и транслировать (в данном случае в обычную кавычку "), а кп 128 зачем транслировать (портить) в знак вопроса?

Можно предложить и менее агрессивный вариант, не требующий добавления отдельного hex-редактора и не вмешивающийся в нынешнюю логику имеющихся кодовых страниц:
![image](https://user-images.githubusercontent.com/49921898/221413180-a44b150a-e90b-4cfa-8d6e-548c83301cd5.png)
Добавить в "Системные" кодировку, например, с названием "Дамп", в которой кодепойнты (кп) с 256-битными кодами сохраняются как есть, one-to-one, а для остальных кп сохранить логику как, например, в OEM.

**Comment by w17** [comment]
@AVBL 
Кодировка 28591 = ISO 8859-1 == Latin I, назовите её 'Дамп' и добавьте в избранные.

**Comment by AVBL** [comment]
Вот, это уже другое дело, можно считать, вопрос решён. Осталось только не забыть про эту кодировку, уж очень она далеко. :(

**Comment by w17** [comment]
В избранных будет ближе. И переименование это тоже не фигура речи. F9 -> Кодовые страницы ....

**Comment by AVBL** [comment]
Это я понял и уже сделал у себя, но я о другом. Настройки могут потеряться при переустановках, да и по другим компьютерам я хожу и там нет моих настроек. А по дефолту эта таблица далеко и память у меня давно уже не юношеская. Про настройку развёртывания окна (из соседнего топика) я, например, забыл.

**Comment by MKadaner** [comment]
> Если я введу с клавиатуры, например, букву "а", то в кодировке OEM она будет иметь код 1072/160, а в кодировке ANSI - 1072/224.

I do not exactly understand the meaning of the phrase "code 1072/160." There are two numbers here, each is a code, but in different coding systems. 1072 is the codepoint number. This is what the editor receives, stores in its internal buffer, and uses to display the glyph on the screen. 160 (or 240) is the byte into which this codepoint will be encoded _if the file is saved in the currently selected code page_. The editor does not use this value while editing, only shows it as a curtesy to the user, and only if it makes sense (different than codepoint, only one byte).

> То есть первичное кодирование редактор проводит и хранит не только кп, но и получившееся значение (в данном случае байт), которое уже и использует при смене кодовой страницы

Not sure I understand this statement. What do you mean by "первичное кодирование"? And no, the editor does not store anything but codepoints.

**Comment by AVBL** [comment]
> I do not exactly understand the meaning of the phrase "code 1072/160."

Ну так всё просто. Я показал, во-первых, что редактор работает не только с кп, а во-вторых, на примере комбинации 1072/224 показал, что при смене её с ANSI на OEM меняется кп (1072 на 1088), но не код (224).

> Not sure I understand this statement. What do you mean by "первичное кодирование"?

Не важно, что именно получает редактор - кп 1072 или код 224, но в результате у него оказываются оба значения - редактор сразу из одного значения получает (транслирует, кодирует) другое.

> And no, the editor does not store anything but codepoints.

И это не совсем так. Откроем файл, в котором есть код, например, 160, в кодировке ANSI. И фар будет хранить и показывать этот код 160. Если мы теперь переключимся в кодировку OEM, то у кода появится кп (1072/160) - но до этого там был только код 160, без кп.

В любом случае, как именно редактор фара хранит файлы в памяти не играет принципиальной роли, поскольку вопрос был в другом - чтобы редактор не портил (не заменял на знаки вопроса) вводимые мной коды. И, как оказалось, таковая возможность имеется, что собственно и снимает вопрос. (Может быть, наверное, имело бы смысл поставить вопрос, чтобы такая особенность была распространена на все 8-битные ANSI и OEM таблицы, но я сейчас обсуждать и давить на эту тему не хотел бы, и так мой доступ к сообществу висит на волоске).
