### ISSUE TITLE
Far regular expressions - performance

### ISSUE THREAD

**Issue by shmuz** [FarGroup/FarManager#741]
I compared the speed of a specific regular expression on three Far Manager installations (on the same computer) and the results show that it becomes slower as years pass.
My test does not cover any significant part of the code, it is just a simple test.
Here are the results:
```
Linux Mint 21 far2m x64  :  622 ms
Windows Far3.0.5629.x64  : 1048 ms
Windows Far3.0.6205.x64  : 1917 ms
```
Here is the test itself:
```lua
local osWindows = package.config:sub(1,1)=="\\"

local s = [[  far.Message(msg, title or "[Highlight] Error", nil, (flags or "").."w")]]
local s_wide
local pat = '".*?"'
local rx_far = regex.new(pat)

if osWindows then
  s_wide = win.Utf8ToUtf16(s)
else
  s_wide = win.Utf8ToUtf32(s)
end

local N = 1e6
local t1 = Far.UpTime
for k=1,N do
  local a = rx_far:findW(s_wide)
  if a=="foo" then break end
end

local t2 = Far.UpTime
far.Show(t2-t1)
```

**Comment by shmuz** [comment]
Here are the results of the same test but regexp was compiled with optimization, i.e. `regex.new(pat, "o")`
```
Linux Mint 21 far2m x64  :  359 ms
Windows Far3.0.5629.x64  :  466 ms
Windows Far3.0.6205.x64  :  830 ms
```

**Comment by alabuzhev** [comment]
There are several contributing factors:
1. [State storage](https://github.com/FarGroup/FarManager/blob/0303fa76c657f92677f0c982c1c8f4156a28f67e/far/RegExp.cpp#L3554) for each lookup is allocated dynamically. In older versions it was part of a regex object itself , subsequent calls could reuse it and don't pay the price. For obvious reasons they could also crash and burn spectacularly from time to time if performed concurrently.
2. For each call we need a [dictionary](https://github.com/FarGroup/FarManager/blob/0303fa76c657f92677f0c982c1c8f4156a28f67e/far/RegExp.cpp#L3537-L3539) to keep group names to support backreferences. Microsoft implementation of associative containers is somewhat suboptimal - it incurs an extra allocation for sentinel nodes, so it's not free even if you don't use named groups. As far as I remember, older versions do not support it at all and thus don't pay the price.
3. Internal interface changes: instead of expecting a fixed buffer of correct size to store matches, the implementation now allocates as much as needed, which is safer and more convenient within Far, but incurs [an extra allocation and an extra copy](https://github.com/FarGroup/FarManager/blob/0303fa76c657f92677f0c982c1c8f4156a28f67e/far/plugapi.cpp#L2840-L2846) when exposed to plugins.

In principle, we can do something about all of these and bring it back to more or less what it was.
However, 0.5-1.5 extra microseconds per call is unlikely a major concern.

**Comment by shmuz** [comment]
> In principle, we can do something about all of these and bring it back to more or less what it was.

If it'll preserve the reliability and correctness then why not :)

>  However, 0.5-1.5 extra microseconds per call is unlikely a major concern.

This is true for cases where regular expression operation is not the major time consumer. But for cases like massive search we have a near 2 times slowdown between 5629 and 6205.

But my main intention was just to attract attention to this issue (in a hope that some easy fix may be available). If there isn't then the reliability and correctness of the code are more important than its speed.

**Comment by alabuzhev** [comment]
Should be somewhat faster in common cases now, without sacrificing neither reliability nor correctness (hopefully).

GCC/Clang builds seem to be marginally faster as well.

**Comment by pasha-zzz** [comment]
6205: 1809 ms (with optimization: 943 ms)
6206: 1179 ms (with optimization: 457 ms)

**Comment by shmuz** [comment]
@alabuzhev 
That was not quite I'd call an easy fix :)

@pasha-zzz
I'll test it when the nightly build is available (to compare apples with apples)

**Comment by pasha-zzz** [comment]
> I'll test it when the nightly build is available

GH release already here... Nightlies are from VS 2019 but GH are from VS 2022

**Comment by shmuz** [comment]
My tests 6206 versus 6205 show an impressive 2.2 times speed growth. Great job!
