### ISSUE TITLE
Editor Undo Glitch

### ISSUE THREAD

**Issue by MKadaner** [FarGroup/FarManager#752]
### Far Manager version

3.0.6167.0

### OS version

Microsoft Windows [Version 10.0.22621.2715]

### Steps to reproduce

1. Start editing a new file (`Shift+F4` Test.txt).
2. Type or paste "The quick brown fox jumps over the lazy dog."
3. Position the caret at the beginning of the word "jumps."
4. Type `Ctr+BS` `Ctr+BS` `Ctrl+Z`.
5. Type `Ctr+BS` `Ctr+BS` `Ctrl+Z` again.

### Expected behavior

The text in the editor reads "The quick brown fox jumps over the lazy dog."

### Actual behavior

The text in the editor disappears.

**Comment by shmuz** [comment]
1. I tried it on the latest build (6218 x86) and **the problem was there**.
2. Then I used my "Far Bisect" script to determine the build where the problem originated. To my surprise all builds (including 6218) didn't show the problem.
3. I exited the script and tried the test on 6218 again. The problem didn't show.
4. Restarted Far - the problem didn't show.

Thus it is clear that it depends on some (currently unknown) condition.

**Comment by alabuzhev** [comment]
> the build where the problem originated

v1.50 beta (6 Oct 1997).

**Comment by alabuzhev** [comment]
Try this:
```DIFF
--- a/far/editor.cpp
+++ b/far/editor.cpp
@@ -1923,6 +1923,7 @@ bool Editor::ProcessKeyInternal(const Manager::Key& Key, bool& Refresh)
 			if (!m_Flags.Check(FEDITOR_LOCKMODE))
 			{
 				Undo(any_of(LocalKey(), KEY_CTRLSHIFTZ, KEY_RCTRLSHIFTZ));
+				m_Flags.Set(FEDITOR_NEWUNDO);
 				Refresh = true;
 			}
```

**Comment by shmuz** [comment]
I found the condition for reproducing this bug.
If we test it on the existing text then the bug does not reproduce but if we enter (or paste) a new text then the bug can be reproduced.

**Comment by MKadaner** [comment]
Does not repro in 6219. Thank you for the fix and super-fast turnaround!
