### ISSUE TITLE
Preserve directories timestamps on copying/moving

### ISSUE THREAD

**Issue by birdie-github** [FarGroup/FarManager#8]
It would be great if Far had an option to preserve directories timestamps while copying/moving directories.

Right now it's impossible and you have to use external applications for that (Total Commander, robocopy, etc.)

**Comment by tvasenin** [comment]
Totally +1 here!

Currently, I use FastCopy to preserve dir timestamps, but would of course prefer Far to be able to do it.

**Comment by alabuzhev** [comment]
Implemented in 40f34a1c15a55adc99604660acda26b9bd7a18e8 / Far 5337

**Comment by tvasenin** [comment]
@alabuzhev @zg0 From the commit, it seems TS are now preserved only on copy, but not on move (FastCopy can do both).

**Comment by alabuzhev** [comment]
@tvasenin have you tried?

**Comment by yegor-mialyk** [comment]
@alabuzhev, with **System.CopyPreserveTimestamps** set to **true**, folders' **Change time** is preserved when copied but it is not preserved when moved within **the same drive**.

**Comment by alabuzhev** [comment]
@yegor-mialyk Change time is a special beast. It's not exposed through regular APIs, not widely used in other apps (I haven't seen any) and provided on "because we can" basis.
When moving within the same volume, the OS preserves other timestamps automatically, without any action from our side.
Given all that, we decided that trying to preserve Change time isn't worth the effort.

**Comment by yegor-mialyk** [comment]
Thanks for the explanation, Alex, fine with me, just tried to understand what did not work for @tvasenin.
