### ISSUE TITLE
CRASH FAR - Exception: 0xC0000005 - STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Zeroes1** [FarGroup/FarManager#875]
### Far Manager version

FAR v3.0.6381.4003 x64

### OS version

10.0.19045.3448

### Other software

-

### Steps to reproduce
FAR с дефолтными настройками
Захожу в %TEMP% под ограниченным юзером

хочу удалить пару папок каких то

C:\temp\OWP6BB5.tmp\

появляется диалог
```
╔════════════════════ Access denied ═════════════════════╗
║ You need to provide administrator permission           ║
║ to open this object:                                   ║
║ \\?\C:\temp\OWP6BB5.tmp\                               ║
║                                                        ║
║ [x] Do this for all current objects                    ║
║ [ ] Do not ask again in the current session            ║
╟────────────────────────────────────────────────────────╢
║                   { ▀▄ OK } [ Skip ]                   ║
╚════════════════════════════════════════════════════════╝
```

выбираю
 [x] Do not ask again in the current session
и OK жму
[без этой опции проблемы - нет]

получаю 100% падение, 100% воспроизводимость

проблема началась
с билда 6377

--------------------------------------------------------------------------------
drkns 2024-09-27 22:42:31+01:00 - build 6377

1. Show content of WCI reparse points

2. New versions of fmt, tinyxml2, Catch2.

трап логи всегда одинаковые генерятся.

приложенная инфа касается CI сборки FAR v3.0.6381.4003 x64
[bug_report.txt](https://github.com/user-attachments/files/17472697/bug_report.txt)
[far.mdmp.zip](https://github.com/user-attachments/files/17472705/far.mdmp.zip)

### Expected behavior

No crash

### Actual behavior

Crash

**Comment by alabuzhev** [comment]
![image](https://github.com/user-attachments/assets/1ae3008d-b774-4a2e-8ab6-16bb14b6e102)

`0x00000028C00000A0` is RBP-10, and RBP is `0x00000028c00000b0`, which is way off, comparing to the local objects.
Interestingly, the high word (`00000028`) looks fine, and the low word looks suspiciously like a valid NTSTATUS code (`C00000A0 The specified named pipe is in the disconnected state`).

[By convention](https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention), RBP is saved and restored by function calls. RBP was used in `File.Open` arguments, so it was fine at that point, since it didn't crash.
Overall it looks like a buffer overflow somewhere in `File.Open` damaged the saved RBP value, but there is nothing particularly interesting in that function. However, it calls other functions and, ultimately, elevation, which uses a named pipe, which could potentially be in the disconnected state (what a nice coincidence).

Having said all that, I cannot reproduce it and don't see anything obviously related in 6377.

**Comment by Zeroes1** [comment]
1) Может быть дело в том что под моей учётной записью (доменный ограниченный юзер) невозможно повысить права?

2) проверил ещё раз ситуацию на старых версиях
Far30b5342.x64.20181112
... 
Far30b6360.x64.20240818
Far30b6376.x64.20240927
тут мы в этой ситуации не падаем
 [x] Do not ask again in the current session
после ответа на вопрос и нажатия OK
получаем в конце
`
╔══════════════════ Error ═══════════════════╗
║          Cannot delete the folder          ║
║                OWPEAD1.tmp                 ║
╟────────────────────────────────────────────╢
║      0x00000005 - Отказано в доступе.      ║
╟────────────────────────────────────────────╢
║ { Retry } [ Skip ] [ Skip all ] [ Cancel ] ║
╚════════════════════════════════════════════╝
`
естественно чтобы выйти либо Skip либо Cancel подходит - прав то у меня нет на доступ.

И именно с Far30b6377.x64.20240929
по
Far30b6382.x64.20241024.7z
включительно в этой ситуации мы 100% падаем.

ps. под локальным админом сделал копию той папки (на ней падаем тоже) под админом удаляется норм. те нарушений файловой системы нет.

3) На всякий случай прикладываю данные падения на Far30b6382.x64.20241024.7z
с map и pdb данными отдельно (кстати как лучше дампы генерить для анализа с map или dmp или без разницы? полный дамп (far_full.mdmp) может лучше помочь в разборе ситуации ?)

[Far30b6382.x64dmp-map.zip](https://github.com/user-attachments/files/17502557/Far30b6382.x64dmp-map.zip)
[Far30b6382.x64dmp-pdb.zip](https://github.com/user-attachments/files/17502558/Far30b6382.x64dmp-pdb.zip)

**Comment by Zeroes1** [comment]
1) наверное 100% важно пытаться делать удаление мимо корзины
 [ ] Удалять в Корзину

2) сделать limited user far легко, если мы работаем под  учёткой с возможностью повышения прав до админа,
путём запуска так:
PsExec64.exe -l C:\path2far\Far.exe

и например попытаться удалить папку C:\Windows\LiveKernelReports 
проверил так - проблема воспроизводится тоже.

3) Сделал тест на Win2016 сервере всё тоже самое
Far30b6376.x64 - не падает
Far30b6382.x64. - падаем
трап похожий.
[W2016-trap.txt.zip](https://github.com/user-attachments/files/17508718/W2016-trap.txt.zip)

ps. почему то трап только в буфер обмена там может запись - постоянно

**Comment by Zeroes1** [comment]
@alabuzhev 
дома всё тоже самое на другой 10ке
Default settings Far30b6377+

[ ] Удалять в Корзину
PsExec64.exe -l C:\path2far\Far.exe

попытался удалить C:\Windows\Minidump 

выбираю
[x] Do not ask again in the current session
на запрос диалога повышения прав, траплог опять похожий

**Comment by Zeroes1** [comment]
fixed. thank you

**Comment by alabuzhev** [comment]
For the sake of history:
- The bug is nicely described [here](https://devblogs.microsoft.com/oldnewthing/20110202-00/?p=11613)
- The bug is over 14 years old
- Apparently all 6377 did is rearranged the stack layout somehow (e.g. due smaller or larger buffers in fmt, better or worse inlining etc.), so that the bug suddenly started hitting something important.

**Comment by Zeroes1** [comment]
@alabuzhev 

ty for the info, very excited reading... 🤨
at work trouble is gone too...  (win10, win2016)
