### ISSUE TITLE
Ctrl + ^ doesn't work to jump to the drive root

### ISSUE THREAD

**Issue by eaexo** [FarGroup/FarManager#887]
### Far Manager version

3.0.6364.0

### OS version

10.0.19045.5131

### Steps to reproduce

press Ctrl + ^

### Expected behavior

when Far is launched and one navigate throw diretory structure once  Ctrl+^ is pressed, it should jump to the directory/disk root.  In previous versions it always jumped into the root of the disk.

As far as I understand that Ctrl + \ does similar thing https://bugs.farmanager.com/view.php?id=4043, however Ctrl + \ does not work on german keyboard, as "\" requires Shift button, see https://en.wikipedia.org/wiki/German_keyboard_layout

In 3.0.6000 Ctrl+^ worked as expected, I used this shortcut for more then 10 years, so it is a breaking change.

It affects both Win10 and Win11.

On the same Win10 machine where Ctrl+^ worked in 3.0.6000, I download 3.0.6364.0 (as 7z), launch it and Ctrl+^ does not work

### Actual behavior

nothing happens

**Comment by alabuzhev** [comment]
Unfortunately, this is one of those wicked problems.

Certain keyboard keys like ,.^`-=#\/ are "OEM" keys, i.e. they are mapped differently on various national keyboards.
Which is a pain if you have multiple keyboard layouts installed and switch between them often, or if you have to go on business trips abroad, because your usual shortcuts, which you often press without even looking, jump all over the place. Or if you want to use keyboard macros created by someone with a different keyboard layout.

To solve this, we switched to a different approach and for these OEM keys we now also take scan codes into account, which means that shortcuts are always mapped to the same *physical* keys, no matter what layout is currently active. Which is awesome if you press them without looking at the keyboard, but not so awesome if you do look at it, because the names might be different from what is written on the keys.

And, since we still needed to name them somehow, we chose to name them as on the US QWERTY keyboard, which is a reasonable default and makes perfect sense to a lot of folks whose native layouts are non-Latin (e.g. Eastern Europe), because US QWERTY is the go-to Latin keyboard for them, but perhaps makes less sense to folks whose native layouts are some forms of extended Latin (e.g. Western Europe).

So, in your case, Ctrl+^ no longer works because we handle this combination as Ctrl+\` (because it's <kbd>`</kbd> on the US keyboard).
And Ctrl+\ now means Ctrl+"the key adjacent to Enter, [as "\\" on the US keyboard](https://en.wikipedia.org/wiki/QWERTY#/media/File:KB_United_States.svg), whatever it's actually called".
In your case it's probably Ctrl+#.

You could say that it's a breaking change indeed. On the other hand, the documentation says nothing about Ctrl+^, only about Ctrl+\\, and there is no `\` printed anywhere on your physical [German](https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:German-T2-Keyboard-Prototype-May-2012.jpg) <kbd>^</kbd> key as far as I can tell, which suggests that the previous implementation was broken anyway.

**Comment by johnd0e** [comment]
Solution is macros.
```lua
Macro {
  area="Shell"; key="Ctrl`"; -- Ctrl^ on German Keyboard
  action=function()
    Keys"CtrlBackSlash"
  end;
}
```

**Comment by eaexo** [comment]
Hello @alabuzhev 

Thanks for the explanation, I wonder if one can make it configurable without macros, as Ctrl+^ on german keyboard is more about layout then the additional key.

the ^ is located in the same row as left ctrl and is quite convenient to handle it with left hand, where as, "#" is a key which rather used by right hand

**Comment by alabuzhev** [comment]
> if one can make it configurable without macros

Not at the moment.
Technically, [the old method](https://github.com/FarGroup/FarManager/commit/d1bd437105c571482db230bfb38acd3f722600b8?diff=split&w=0#diff-5bf7d4e12fa5e2a476c57db78b0a879bd9ffe768351f0d47210862d7d025761aL1874-R1900) didn't make any sense for German (and quite a few other) keyboards, but it was like that for decades, so perhaps a configuration option will be justified.
Any particular reasons to avoid macros? It is the 'official' way to redefine keys.

**Comment by eaexo** [comment]
thanks
